# App
FPS = 60

# GUI
TILE = 16
ROW = 20
COL = 30
WIDTH = COL * TILE
HEIGHT = ROW * TILE
GAME_BOARD_SIZE = (WIDTH, HEIGHT)
TOP_BAR_SIZE = (WIDTH, TILE * 2)
BOTTOM_BAR_SIZE = (WIDTH, TILE * 2)
DISPLAY_SIZE = (WIDTH, HEIGHT + TILE * 4)
TITLE = 'SPACE GUARDIAN'

# Font
FONT_SIZE = 16
TEXT_COLOR = (255, 255, 255)

# Colors
WHITE = '#FFFFFF'
BLACK = '#000000'
YELLOW = '#FFFF00'
RED = '#FF0000'
GREEN = '#00FF00'

# Directions
UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3
